### ISSUE TITLE
Questions about "need_norm"

### ISSUE THREAD

**Issue by pengsida** [lzx551402/ASLFeat#1]
Hi, deer author,

I find that you use `need_norm` in `def our_score()` https://github.com/lzx551402/ASLFeat/blob/master/models/cnn_wrapper/aslfeat.py#L106
However, you does not talk about this normalization.
Could you tell me that how it affects the performance?

**Comment by lzx551402** [comment]
This normalization is used to improve the convergence, as also used by D2-Net (https://github.com/mihaidusmanu/d2-net/blob/master/lib/model.py#L62). Otherwise we often encounter NAN value when trained from scratch.

A bit different from D2-Net, I update this normalization term in a moving-average fashion, so that the magnitude of detection scores is consistent across different images, making the score threshold more meaningful.

**Comment by pengsida** [comment]
Thanks for your prompt reply!
